
include: package:flutter_lints/flutter.yaml

linter:

  rules:
    constant_identifier_names: false
    non_constant_identifier_names: false
    use_key_in_widget_constructors: false
    invalid_use_of_visible_for_testing_member: false
    must_be_immutable: false

